#pragma once

enum E_ELEMKIND_TYPE
{
	E_ELEMKIND_UNKNOWN = 0
	, E_ELEMKIND_0D = 0
	, E_ELEMKIND_1D
	, E_ELEMKIND_2D
	, E_ELEMKIND_3D
	, E_ELEMKIND_ETC

	, E_ELEMKIND_NUM
};

enum E_ELEMENT_TYPE
{
	E_ELEMTYPE_UNKNOWN = 0			// Unknown
	, E_ELEMTYPE_VERTEX				// 0D
	, E_ELEMTYPE_LINE2				// 1D
	, E_ELEMTYPE_LINE3				// 1D
	, E_ELEMTYPE_TRI3				// 2D TRI
	, E_ELEMTYPE_TRI6				// 2D Parabolic TRI
	, E_ELEMTYPE_QUAD4				// 2D QUAD
	, E_ELEMTYPE_QUAD8				// 2D Parabolic QUAD
	, E_ELEMTYPE_TET4				// 3D TETRA
	, E_ELEMTYPE_TET10				// 3D Parabolic TETRA
	, E_ELEMTYPE_PYRAMID5			// 3D PYRAMID
	, E_ELEMTYPE_PYRAMID13			// 3D Parabolic PYRAMID
	, E_ELEMTYPE_WEDGE6				// 3D WEDGE
	, E_ELEMTYPE_WEDGE15			// 3D Parabolic Wedge
	, E_ELEMTYPE_HEX8				// 3D HEXA
	, E_ELEMTYPE_HEX20				// 3D Parabolic HEXA

	, E_ELEMTYPE_NUM
};